"""Draw AI-generated illustrations in the isomer.ai style into illustrations/new/.

These were generated by Claude (Anthropic's AI), not drawn by a designer.

    python3 scripts/draw_illustrations.py

The isomer.ai set is drawn in Figma; these follow its vocabulary so they sit beside it:
a 2px Isomer Blue outline with square corners, flat fills from one accent family per
illustration (orange, purple or lime) plus white and cool gray, documents with folded
corners, envelopes, "!" and check badges, the "Ai" tile, offset duplicates for depth,
and thick pale strokes under highlighted lines. No gradients and no live text.
"""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "illustrations" / "new"

INK = "#000441"
GRAY = "#DADFE8"
ORANGE, PEACH = "#FF9E6E", "#FFE0D4"
PURPLE, LAVENDER, LILAC, MIST = "#9288FF", "#BCB6FF", "#CFCBFF", "#E8ECFF"
LIME, PALE_LIME = "#D5F22A", "#F5F9D6"
S = f'stroke="{INK}" stroke-width="2" stroke-miterlimit="10"'


def svg(body, title, w=160, h=160):
    return (f'<svg width="{w}" height="{h}" viewBox="0 0 {w} {h}" fill="none" '
            f'xmlns="http://www.w3.org/2000/svg">\n'
            f'<!-- Generated by Claude (Anthropic AI) in the isomer.ai illustration style. Not drawn by a designer. -->\n'
            f'<title>{title}</title>\n{body}\n</svg>\n')


def rect(x, y, w, h, fill="white"):
    return f'<path d="M{x} {y}H{x + w}V{y + h}H{x}Z" fill="{fill}" {S}/>'


def line(*pts, width=2, color=INK, dash=None):
    d = "M" + " L".join(f"{x} {y}" for x, y in pts)
    extra = f' stroke-dasharray="{dash}"' if dash else ""
    return f'<path d="{d}" stroke="{color}" stroke-width="{width}" stroke-miterlimit="10"{extra}/>'


def doc(x, y, w, h, fill="white", fold=12, lines=(), hl=None, hl_color=GRAY):
    """A page with a folded corner. lines: (y_offset, length) pairs; hl: index of the highlighted line."""
    out = [f'<path d="M{x} {y}H{x + w - fold}L{x + w} {y + fold}V{y + h}H{x}Z" fill="{fill}" {S}/>',
           f'<path d="M{x + w - fold} {y}V{y + fold}H{x + w}" {S}/>']
    for i, (dy, ln) in enumerate(lines):
        if i == hl:
            out.append(line((x + 9, y + dy), (x + 9 + ln, y + dy), width=8, color=hl_color))
        out.append(line((x + 9, y + dy), (x + 9 + ln, y + dy)))
    return "\n".join(out)


def shadow_doc(x, y, w, h, fill, dx=8, dy=8, fold=12):
    return f'<path d="M{x + dx} {y + dy}H{x + dx + w - fold}L{x + dx + w} {y + dy + fold}V{y + dy + h}H{x + dx}Z" fill="{fill}" {S}/>'


def envelope(x, y, w, h, fill="white", flap=None):
    out = [rect(x, y, w, h, fill)]
    if flap:
        out.append(line((x + 3, y + 5), (x + w / 2, y + h * 0.58), (x + w - 3, y + 5), width=7, color=flap))
    out.append(line((x, y), (x + w / 2, y + h * 0.6), (x + w, y)))
    return "\n".join(out)


def circle(cx, cy, r, fill="white"):
    return f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="{fill}" {S}/>'


def alert(cx, cy, r=14, fill=PEACH):
    return "\n".join([circle(cx, cy, r, fill),
                      f'<path d="M{cx - 1.25} {cy - r * 0.55}H{cx + 1.25}V{cy + r * 0.12}H{cx - 1.25}Z" fill="{INK}"/>',
                      f'<circle cx="{cx}" cy="{cy + r * 0.42}" r="1.7" fill="{INK}"/>'])


def check(cx, cy, r=13, fill=PURPLE):
    return "\n".join([circle(cx, cy, r, fill),
                      line((cx - r * 0.5, cy), (cx - r * 0.12, cy + r * 0.42), (cx + r * 0.55, cy - r * 0.42))])


def cross(cx, cy, r=11, fill=PEACH):
    k = r * 0.38
    return "\n".join([circle(cx, cy, r, fill),
                      line((cx - k, cy - k), (cx + k, cy + k)), line((cx + k, cy - k), (cx - k, cy + k))])


def dollar(cx, cy, s=1.0, width=2.5):
    d = (f"M{cx + 6 * s} {cy - 7 * s}C{cx + 4 * s} {cy - 10 * s} {cx - 6 * s} {cy - 10 * s} {cx - 6 * s} {cy - 4 * s}"
         f"C{cx - 6 * s} {cy + 1 * s} {cx + 6 * s} {cy - 1 * s} {cx + 6 * s} {cy + 4 * s}"
         f"C{cx + 6 * s} {cy + 10 * s} {cx - 4 * s} {cy + 10 * s} {cx - 6 * s} {cy + 7 * s}"
         f"M{cx} {cy - 12 * s}V{cy + 12 * s}")
    return f'<path d="{d}" stroke="{INK}" stroke-width="{width}" stroke-miterlimit="10"/>'


def ai_tile(x, y, w, h, fill=LIME):
    """The 'Ai' tile, with the letters drawn as strokes."""
    ax, base, top = x + w * 0.2, y + h * 0.78, y + h * 0.26
    aw = w * 0.36
    return "\n".join([rect(x, y, w, h, fill),
                      f'<path d="M{ax} {base}L{ax + aw / 2} {top}L{ax + aw} {base}M{ax + aw * 0.2} {base - (base - top) * 0.36}H{ax + aw * 0.8}" stroke="{INK}" stroke-width="2.5" stroke-miterlimit="10"/>',
                      line((x + w * 0.74, y + h * 0.44), (x + w * 0.74, base), width=2.5),
                      f'<circle cx="{x + w * 0.74}" cy="{y + h * 0.31}" r="1.9" fill="{INK}"/>'])


def arrow_head(x, y, direction, size=6):
    pts = {"up": [(x - size, y + size), (x, y), (x + size, y + size)],
           "down": [(x - size, y - size), (x, y), (x + size, y - size)],
           "left": [(x + size, y - size), (x, y), (x + size, y + size)],
           "right": [(x - size, y - size), (x, y), (x - size, y + size)]}[direction]
    return line(*pts)


def person(cx, top, head=13, fill=LAVENDER, body_fill=MIST, width=54):
    """Circle head, curved shoulders, flat base, as in the isomer.ai career and specialist art."""
    hy = top + head
    sy = hy + head + 6
    half = width / 2
    return "\n".join([
        f'<path d="M{cx - half} {sy + 30}C{cx - half} {sy + 8} {cx - half * 0.55} {sy} {cx} {sy}C{cx + half * 0.55} {sy} {cx + half} {sy + 8} {cx + half} {sy + 30}Z" fill="{body_fill}" {S}/>',
        circle(cx, hy, head, fill)])


# Each illustration: (file stem, title, body)
ART = []


def art(stem, title):
    def wrap(fn):
        ART.append((stem, title, fn))
        return fn
    return wrap


@art("time-limited-demand", "Time-limited demand")
def _():
    return "\n".join([
        shadow_doc(30, 20, 78, 104, PEACH),
        doc(30, 20, 78, 104, lines=[(22, 44), (34, 56), (46, 36), (62, 56), (74, 48)], hl=3, hl_color=ORANGE),
        circle(114, 112, 26, ORANGE),
        *[line((114 + dx * 21, 112 + dy * 21), (114 + dx * 25, 112 + dy * 25)) for dx, dy in ((0, -1), (1, 0), (0, 1), (-1, 0))],
        line((114, 112), (114, 95)), line((114, 112), (126, 120)),
        f'<circle cx="114" cy="112" r="3" fill="{INK}"/>',
        alert(126, 26),
    ])


@art("subrogation-recovery", "Subrogation recovery")
def _():
    return "\n".join([
        doc(12, 44, 54, 70, lines=[(18, 26), (28, 34), (38, 22), (48, 30)]),
        doc(94, 44, 54, 70, PALE_LIME, lines=[(18, 26), (28, 34), (38, 22), (48, 30)], hl=1, hl_color=LIME),
        rect(62, 12, 36, 36, LIME), dollar(80, 30),
        line((121, 44), (121, 30), (98, 30)), arrow_head(98, 30, "left"),
        line((121, 114), (121, 134), (39, 134), (39, 120)), arrow_head(39, 116, "up"),
        check(56, 106, 13, LIME),
    ])


@art("attorney-representation", "Attorney representation")
def _():
    return "\n".join([
        person(46, 26, head=14, fill=PURPLE, body_fill=LAVENDER, width=60),
        rect(30, 86, 30, 22, LILAC), line((40, 86), (40, 80), (50, 80), (50, 86)),
        envelope(66, 74, 80, 54, "white", flap=GRAY),
        alert(136, 64, 14, LILAC),
    ])


@art("fraud-ring-detection", "Fraud ring detection")
def _():
    nodes = {"a": (26, 34), "b": (70, 22), "c": (132, 30), "d": (40, 92), "e": (92, 82), "f": (118, 112), "g": (74, 132)}
    edges = [("a", "b"), ("b", "c"), ("a", "d"), ("b", "e"), ("c", "e"), ("d", "g"), ("e", "f"), ("e", "g"), ("f", "g"), ("c", "f")]
    ring = {"e", "f", "g"}
    out = [circle(98, 108, 34, PEACH)]
    for p, q in edges:
        hot = p in ring and q in ring
        out.append(line(nodes[p], nodes[q], width=3.2 if hot else 2))
    for k, (x, y) in nodes.items():
        out.append(circle(x, y, 9, ORANGE if k in ring else "white"))
    out.append(line((122, 132), (146, 152), width=6))
    out.append(f'<circle cx="98" cy="108" r="34" stroke="{INK}" stroke-width="2"/>')
    return "\n".join(out)


@art("medical-bill-review", "Medical bill review")
def _():
    rows = []
    for i, (y, mark) in enumerate([(64, "ok"), (82, "ok"), (100, "flag")]):
        rows.append(line((44, y), (82, y)))
        rows.append(rect(92, y - 7, 14, 14, LILAC if mark == "ok" else "white"))
        if mark == "ok":
            rows.append(line((95, y), (98.5, y + 3.5), (103.5, y - 3.5)))
    return "\n".join([
        shadow_doc(30, 18, 86, 116, LILAC),
        doc(30, 18, 86, 116, lines=[(14, 30)]),
        rect(80, 26, 24, 24, PURPLE),
        f'<path d="M89.5 31H94.5V35.5H99V40.5H94.5V45H89.5V40.5H85V35.5H89.5Z" fill="white" {S}/>',
        *rows,
        line((44, 118), (100, 118), width=8, color=GRAY), line((44, 118), (100, 118)),
        alert(124, 102, 14, PEACH),
    ])


@art("catastrophe-surge", "Catastrophe surge")
def _():
    cloud = (f'<path d="M22 52C14 52 10 46 10 41C10 35 15 31 21 31C22 22 30 16 39 16C47 16 53 21 55 28'
             f'C57 27 59 27 61 27C68 27 74 33 74 40C74 47 68 52 61 52Z" fill="{PALE_LIME}" {S}/>')
    bolt = f'<path d="M44 46L34 66H44L38 82L58 58H47L53 46Z" fill="{LIME}" {S}/>'
    return "\n".join([
        cloud, bolt,
        envelope(58, 62, 64, 42, PALE_LIME),
        envelope(68, 78, 64, 42, "white"),
        envelope(78, 94, 64, 42, "white", flap=LIME),
        line((148, 84), (148, 22)), arrow_head(148, 22, "up"),
    ])


@art("reserve-adequacy", "Reserve adequacy")
def _():
    return "\n".join([
        f'<path d="M24 98A56 56 0 0 1 136 98Z" fill="{PEACH}" {S}/>',
        f'<path d="M100 98A20 20 0 0 0 60 98" fill="white"/>',
        f'<path d="M108.6 50.5A56 56 0 0 1 136 98H116A36 36 0 0 0 98 67.4Z" fill="{ORANGE}" {S}/>',
        *[line((80 + 46 * c, 98 - 46 * s), (80 + 56 * c, 98 - 56 * s)) for c, s in ((-1, 0), (-0.707, 0.707), (0, 1), (0.707, 0.707), (1, 0))],
        line((80, 98), (110, 62), width=2.5), circle(80, 98, 6, INK),
        line((14, 98), (146, 98)),
        rect(62, 110, 36, 36, ORANGE), dollar(80, 128),
        line((136, 140), (136, 112)), arrow_head(136, 112, "up"),
    ])


@art("cross-claim-patterns", "Cross-claim patterns")
def _():
    docs = [(6, 12), (57, 28), (108, 12)]
    out = []
    for x, y in docs:
        out.append(doc(x, y, 46, 62, lines=[(18, 26), (30, 20), (42, 26)], hl=1, hl_color=LAVENDER))
    out += [line((29, 74), (29, 132), (64, 132), dash="5 5"),
            line((80, 90), (80, 116), dash="5 5"),
            line((131, 74), (131, 132), (96, 132), dash="5 5"),
            alert(80, 132, 16, PURPLE)]
    return "\n".join(out)


@art("multichannel-intake", "Multichannel intake")
def _():
    tiles = [(12, 14), (12, 50), (12, 86), (12, 122)]
    glyphs = [
        line((15, 17), (28, 26), (41, 17)),                                   # email
        "\n".join([line((20, 56), (34, 56)), line((20, 61), (34, 61)), line((20, 66), (30, 66))]),  # fax / document
        f'<path d="M18 98C22 92 26 104 30 98C34 92 38 104 42 98" stroke="{INK}" stroke-width="2"/>',  # voice
        "\n".join([line((12, 130), (44, 130)), f'<circle cx="17" cy="126" r="1.4" fill="{INK}"/>']),  # portal
    ]
    out = []
    for (x, y), g in zip(tiles, glyphs):
        out += [rect(x, y, 32, 24, "white"), g, line((44, y + 12), (66, y + 12))]
    out += [line((66, 26), (66, 134)), line((66, 80), (88, 80)),
            rect(88, 48, 60, 64, PALE_LIME),
            ai_tile(98, 58, 40, 36, LIME),
            line((98, 102), (138, 102))]
    return "\n".join(out)


@art("bad-faith-exposure", "Bad-faith exposure")
def _():
    return "\n".join([
        line((80, 28), (80, 130)), line((30, 44), (130, 44)),
        circle(80, 28, 6, ORANGE),
        line((30, 44), (16, 84)), line((30, 44), (44, 84)),
        line((130, 44), (116, 84)), line((130, 44), (144, 84)),
        f'<path d="M12 84H48C48 94 40 100 30 100C20 100 12 94 12 84Z" fill="{PEACH}" {S}/>',
        f'<path d="M112 84H148C148 94 140 100 130 100C120 100 112 94 112 84Z" fill="{PEACH}" {S}/>',
        rect(20, 62, 20, 22, "white"), line((24, 70), (36, 70)), line((24, 76), (32, 76)),
        alert(130, 70, 13, ORANGE),
        rect(54, 130, 52, 12, "white"),
    ])


@art("deadline-calendar", "Deadline calendar")
def _():
    out = [rect(18, 30, 124, 108, "white"), rect(18, 30, 124, 24, PURPLE),
           line((48, 22), (48, 38)), line((112, 22), (112, 38))]
    cw, ch = 124 / 6, 84 / 4
    for r in range(4):
        for c in range(6):
            x, y = 18 + c * cw, 54 + r * ch
            passed = r * 6 + c < 9
            if passed:
                out.append(f'<path d="M{x} {y}H{x + cw}V{y + ch}H{x}Z" fill="{MIST}"/>')
    for c in range(1, 6):
        out.append(line((18 + c * cw, 54), (18 + c * cw, 138), width=1, color=GRAY))
    for r in range(1, 4):
        out.append(line((18, 54 + r * ch), (142, 54 + r * ch), width=1, color=GRAY))
    out.append(rect(18, 30, 124, 108, "none"))
    tx, ty = 18 + 4 * cw, 54 + 2 * ch
    out.append(f'<path d="M{tx} {ty}H{tx + cw}V{ty + ch}H{tx}Z" fill="{PURPLE}" {S}/>')
    out.append(line((tx + 5, ty + ch / 2), (tx + 9, ty + ch / 2 + 4), (tx + cw - 5, ty + 5)))
    out.append(alert(tx + cw, ty - 2, 13, PEACH))
    return "\n".join(out)


@art("adjuster-workload", "Adjuster workload")
def _():
    out = []
    for i in range(6):
        out.append(envelope(8, 118 - i * 18, 54, 32, "white" if i % 2 else PALE_LIME))
    out += [line((70, 86), (90, 86)), arrow_head(90, 86, "right"),
            person(120, 34, head=15, fill=LIME, body_fill=PALE_LIME, width=62),
            envelope(98, 112, 46, 30, "white", flap=GRAY),
            check(144, 62, 13, LIME)]
    return "\n".join(out)


# ---- Helpers for the second set ----

def dashed_rect(x, y, w, h, fill="none"):
    return f'<path d="M{x} {y}H{x + w}V{y + h}H{x}Z" fill="{fill}" {S} stroke-dasharray="5 4"/>'


def folder(x, y, w, h, fill="white"):
    return f'<path d="M{x} {y}H{x + 18}L{x + 24} {y + 6}H{x + w}V{y + h}H{x}Z" fill="{fill}" {S}/>'


def drop(cx, cy, fill):
    return (f'<path d="M{cx} {cy - 9}C{cx + 6} {cy - 1} {cx + 6} {cy + 6} {cx} {cy + 6}'
            f'C{cx - 6} {cy + 6} {cx - 6} {cy - 1} {cx} {cy - 9}Z" fill="{fill}" {S}/>')


def briefcase(x, y, w, h, fill):
    hw = w * 0.32
    return "\n".join([line((x + hw, y), (x + hw, y - 6), (x + w - hw, y - 6), (x + w - hw, y)),
                      rect(x, y, w, h, fill), line((x, y + h * 0.4), (x + w, y + h * 0.4))])


def clock(cx, cy, r, fill, hands=((0, -0.7), (0.5, 0.25))):
    out = [circle(cx, cy, r, fill)]
    out += [line((cx + dx * (r - 6), cy + dy * (r - 6)), (cx + dx * (r - 2), cy + dy * (r - 2)))
            for dx, dy in ((0, -1), (1, 0), (0, 1), (-1, 0))]
    out += [line((cx, cy), (cx + hx * r, cy + hy * r)) for hx, hy in hands]
    out.append(f'<circle cx="{cx}" cy="{cy}" r="2.5" fill="{INK}"/>')
    return "\n".join(out)


def text_lines(x, y, lengths, gap=10):
    return "\n".join(line((x, y + i * gap), (x + ln, y + i * gap)) for i, ln in enumerate(lengths))


# ---- Second set: topics from the isomer.ai blog and the commercial claims pitch ----

@art("day-zero", "Day 0, before first notice")
def _():
    return "\n".join([
        clock(46, 42, 22, ORANGE),
        envelope(14, 78, 48, 30, PEACH),
        envelope(24, 88, 48, 30, "white", flap=ORANGE),
        alert(70, 84, 12),
        dashed_rect(100, 66, 44, 52),
        text_lines(108, 80, (24, 28, 18)),
        line((12, 132), (146, 132)), arrow_head(146, 132, "right"),
        line((48, 124), (48, 140)), line((122, 124), (122, 140)),
    ])


@art("inbox-control-layer", "The inbox as the control layer")
def _():
    return "\n".join([
        envelope(30, 62, 56, 36, "white"),
        envelope(70, 70, 56, 36, MIST, flap=LAVENDER),
        f'<path d="M16 96H52L58 108H102L108 96H144V140H16Z" fill="{LILAC}" {S}/>',
        line((16, 50), (144, 50), width=3, color=PURPLE),
        ai_tile(60, 12, 40, 30, PURPLE),
    ])


@art("adjuster-variance", "Two adjusters, same email")
def _():
    return "\n".join([
        envelope(56, 12, 48, 32, PALE_LIME, flap=LIME),
        line((80, 44), (80, 54)), line((36, 54), (124, 54)),
        line((36, 54), (36, 64)), line((124, 54), (124, 64)),
        person(36, 66, head=12, fill=LIME, body_fill=PALE_LIME, width=50),
        person(124, 66, head=12, fill="white", body_fill=PALE_LIME, width=50),
        check(60, 122, 11, LIME),
        cross(148, 122, 11, "white"),
    ])


@art("explainable-decision", "Explainable decision")
def _():
    return "\n".join([
        shadow_doc(14, 22, 64, 88, LILAC),
        doc(14, 22, 64, 88, lines=[(20, 30), (32, 44), (48, 40), (60, 34), (72, 44)], hl=2, hl_color=LAVENDER),
        line((68, 70), (98, 70), dash="4 4"),
        rect(98, 50, 48, 40, LILAC), check(122, 70, 12, PURPLE),
        line((122, 90), (122, 110)),
        rect(98, 110, 14, 14, "white"), rect(115, 110, 14, 14, LAVENDER), rect(132, 110, 14, 14, "white"),
    ])


@art("vendor-ai-responsibility", "Vendor AI is still your responsibility")
def _():
    return "\n".join([
        shadow_doc(18, 16, 74, 100, PEACH),
        doc(18, 16, 74, 100, lines=[(20, 40), (32, 52), (44, 46), (56, 52)]),
        f'<path d="M28 98C34 90 38 104 44 96C48 91 52 100 58 96" stroke="{INK}" stroke-width="2"/>',
        line((26, 104), (70, 104)),
        ai_tile(86, 82, 58, 54, ORANGE),
        alert(140, 76, 13),
    ])


@art("decision-audit-trail", "Decision audit trail")
def _():
    out = [line((22, 31), (22, 121))]
    for i in range(4):
        y = 20 + i * 30
        hot = i == 2
        out += [rect(38, y, 104, 22, PALE_LIME if hot else "white"),
                line((46, y + 11), (46 + (60 if i % 2 else 76), y + 11)),
                circle(22, y + 11, 5, LIME if hot else "white")]
    out += [circle(110, 91, 20, "none"), line((124, 105), (142, 123), width=6)]
    return "\n".join(out)


@art("claims-leakage", "Claims leakage")
def _():
    return "\n".join([
        rect(10, 38, 62, 24, "white"), rect(88, 38, 62, 24, "white"),
        rect(68, 32, 24, 36, PEACH),
        line((80, 32), (80, 46)),
        drop(80, 84, ORANGE), drop(80, 104, PEACH),
        rect(62, 118, 36, 36, ORANGE), dollar(80, 136),
        line((18, 50), (60, 50), width=8, color=GRAY), line((100, 50), (142, 50), width=8, color=GRAY),
    ])


@art("claim-matching", "Matching messages to the claim")
def _():
    out = []
    for y in (22, 67, 112):
        out += [envelope(10, y, 40, 26, "white"), line((50, y + 13), (74, y + 13), (74, 80) if y != 67 else (74, 80))]
    out += [line((74, 80), (96, 80)), arrow_head(96, 80, "right"),
            folder(100, 18, 48, 34), folder(100, 63, 48, 34, LILAC), folder(100, 108, 48, 34),
            check(146, 66, 11, PURPLE)]
    return "\n".join(out)


@art("claim-graph", "Claim graph")
def _():
    return "\n".join([
        line((28, 38), (80, 78)), line((136, 44), (80, 78)), line((30, 126), (80, 78)), line((132, 126), (80, 78)),
        line((28, 38), (30, 108), dash="4 4"),
        envelope(10, 22, 36, 24, "white"),
        person(136, 12, head=9, fill=LIME, body_fill=PALE_LIME, width=36),
        doc(14, 108, 32, 38, lines=[(16, 12), (24, 14)]),
        rect(116, 112, 34, 30, "white"), rect(116, 112, 34, 10, LIME),
        doc(58, 50, 44, 56, PALE_LIME, lines=[(20, 22), (30, 26), (40, 18)], hl=1, hl_color=LIME),
    ])


@art("open-claims-layer", "Open claims layer")
def _():
    tiles = [(12, 14), (112, 14), (12, 118), (112, 118)]
    glyphs = [
        "\n".join([line((20, 24), (40, 24)), line((20, 32), (34, 32))]),
        "\n".join([line((122, 36), (122, 28)), line((130, 36), (130, 22)), line((138, 36), (138, 26))]),
        "\n".join([line((12, 126), (48, 126)), line((20, 134), (40, 134))]),
        "\n".join([line((126, 126), (120, 132), (126, 138)), line((134, 126), (140, 132), (134, 138))]),
    ]
    out = [line((48, 42), (60, 56)), line((112, 42), (100, 56)), line((48, 118), (60, 104)), line((112, 118), (100, 104))]
    for (x, y), g in zip(tiles, glyphs):
        out += [rect(x, y, 36, 28, "white"), g]
    out += [rect(51, 46, 6, 6, LAVENDER), rect(103, 46, 6, 6, LAVENDER), rect(51, 108, 6, 6, LAVENDER), rect(103, 108, 6, 6, LAVENDER)]
    out.append(ai_tile(56, 56, 48, 48, PURPLE))
    return "\n".join(out)


@art("consistent-results", "The same read every time")
def _():
    out = []
    for x in (14, 58, 102):
        out += [doc(x, 22, 44, 60, lines=[(18, 24), (30, 18), (42, 24)], hl=1, hl_color=LIME),
                check(x + 22, 104, 12, LIME)]
    out += [line((14, 134), (146, 134))] + [line((x, 128), (x, 140)) for x in (36, 80, 124)]
    return "\n".join(out)


@art("signal-library", "Configurable signal library")
def _():
    out = [rect(20, 14, 120, 132, "white"), rect(20, 14, 120, 24, PEACH)]
    for i, on in enumerate((True, False, True, True)):
        y = 50 + i * 24
        out += [rect(30, y, 16, 16, ORANGE if on else "white"), line((54, y + 8), (54 + (40 if i % 2 else 32), y + 8)),
                rect(104, y + 2, 26, 12, PEACH if on else "white"),
                rect(118 if on else 106, y + 4, 10, 8, ORANGE if on else GRAY)]
    return "\n".join(out)


@art("entity-resolution", "One policyholder, many spellings")
def _():
    def card(x, y, w, h, fill, hl):
        out = [rect(x, y, w, h, fill), circle(x + 14, y + h / 2, 8, LAVENDER)]
        if hl:
            out.append(line((x + 28, y + h / 2 - 6), (x + 48, y + h / 2 - 6), width=8, color=LAVENDER))
        out += [line((x + 28, y + h / 2 - 6), (x + 48, y + h / 2 - 6)), line((x + 28, y + h / 2 + 6), (x + 42, y + h / 2 + 6))]
        return out
    out = card(12, 26, 56, 40, "white", False) + card(12, 94, 56, 40, "white", True)
    out += [line((68, 46), (82, 46), (82, 114), (68, 114)), line((82, 80), (94, 80)), arrow_head(94, 80, "right")]
    out += card(98, 58, 52, 44, LILAC, False)
    out.append(check(148, 58, 11, PURPLE))
    return "\n".join(out)


@art("litigation-funding", "Litigation funding")
def _():
    return "\n".join([
        rect(20, 23, 36, 36, ORANGE), dollar(38, 41),
        line((62, 41), (88, 41)), arrow_head(88, 41, "right"),
        rect(12, 72, 52, 14, PEACH), rect(12, 86, 52, 14, "white"), rect(12, 100, 52, 14, PEACH), rect(12, 114, 52, 14, "white"),
        rect(114, 52, 8, 64, "white"),
        rect(94, 28, 48, 24, ORANGE), line((104, 28), (104, 52)), line((132, 28), (132, 52)),
        rect(90, 116, 56, 12, PEACH),
        line((8, 136), (152, 136)),
    ])


@art("plaintiff-ai", "Plaintiff AI at scale")
def _():
    lines_ = [(18, 26), (28, 20), (38, 26)]
    return "\n".join([
        ai_tile(12, 58, 44, 44, PURPLE),
        line((60, 80), (86, 80)), arrow_head(86, 80, "right"),
        doc(82, 12, 48, 60, MIST, lines=lines_),
        doc(92, 44, 48, 60, "white", lines=lines_),
        doc(102, 80, 48, 60, "white", lines=lines_, hl=1, hl_color=LAVENDER),
        alert(130, 14, 12, LILAC),
    ])


@art("legal-advertising", "Legal advertising")
def _():
    return "\n".join([
        rect(44, 96, 8, 40, "white"), rect(108, 96, 8, 40, "white"),
        rect(14, 22, 132, 74, PALE_LIME),
        rect(34, 14, 12, 8, LIME), rect(114, 14, 12, 8, LIME),
        circle(46, 52, 14, LIME),
        f'<path d="M26 82C26 72 36 68 46 68C56 68 66 72 66 82Z" fill="white" {S}/>',
        line((80, 44), (132, 44)),
        line((80, 60), (124, 60), width=8, color=LIME), line((80, 60), (124, 60)),
        line((80, 76), (112, 76)),
        line((8, 136), (152, 136)),
    ])


@art("social-inflation", "Social inflation")
def _():
    heights = (28, 40, 56, 76, 100)
    out = []
    for i, h in enumerate(heights):
        x = 16 + i * 26
        out.append(rect(x, 132 - h, 20, h, ORANGE if i == 4 else PEACH))
    out += [line((10, 110), (150, 82), dash="5 4"), line((8, 132), (152, 132)), alert(132, 16, 12)]
    return "\n".join(out)


@art("litigated-claim-cost", "What a lawyer does to claim cost")
def _():
    out = [rect(18, 108, 32, 32, MIST), dollar(34, 124, 0.7, 2)]
    for r, y in enumerate((108, 76, 44)):
        for c, x in enumerate((84, 116)):
            out += [rect(x, y, 32, 32, PURPLE if (r, c) == (2, 1) else LILAC), dollar(x + 16, y + 16, 0.7, 2)]
    out += [briefcase(100, 16, 32, 22, LAVENDER), line((8, 140), (152, 140))]
    return "\n".join(out)


@art("early-representation", "A lawyer within 24 hours")
def _():
    return "\n".join([
        circle(50, 70, 36, PALE_LIME),
        f'<path d="M50 70V34A36 36 0 0 1 86 70Z" fill="{LIME}" {S}/>',
        *[line((50 + dx * 30, 70 + dy * 30), (50 + dx * 36, 70 + dy * 36)) for dx, dy in ((0, -1), (1, 0), (0, 1), (-1, 0))],
        line((50, 70), (50, 46)), line((50, 70), (70, 70)), f'<circle cx="50" cy="70" r="3" fill="{INK}"/>',
        person(120, 46, head=13, fill=LIME, body_fill=PALE_LIME, width=52),
        briefcase(106, 104, 28, 22, "white"),
        line((8, 136), (152, 136)),
    ])


@art("litigation-hold", "Litigation hold")
def _():
    return "\n".join([
        doc(42, 18, 40, 44, lines=[(16, 16), (26, 20)]),
        doc(78, 26, 40, 36, MIST, lines=[(14, 16)]),
        rect(32, 70, 96, 70, "white"),
        rect(24, 54, 112, 18, LILAC),
        f'<path d="M72 106V98C72 90 88 90 88 98V106" stroke="{INK}" stroke-width="2"/>',
        rect(66, 106, 28, 22, PURPLE),
        line((80, 114), (80, 120), width=3),
    ])


@art("deleted-messages", "Deleted messages")
def _():
    return "\n".join([
        rect(40, 10, 80, 140, "white"), line((40, 24), (120, 24)), line((40, 136), (120, 136)),
        rect(48, 32, 44, 18, GRAY),
        rect(68, 56, 44, 18, PEACH),
        dashed_rect(48, 80, 44, 18),
        rect(68, 104, 44, 18, PEACH),
        alert(118, 89, 14, ORANGE),
    ])


@art("handler-alert", "To the handler in 30 minutes")
def _():
    return "\n".join([
        circle(38, 42, 22, PALE_LIME),
        f'<path d="M38 42V20A22 22 0 0 1 38 64Z" fill="{LIME}" {S}/>',
        rect(34, 14, 8, 6, "white"),
        f'<path d="M64 112H136L126 98V76C126 58 114 46 100 46C86 46 74 58 74 76V98Z" fill="{LIME}" {S}/>',
        circle(100, 40, 5, "white"), circle(100, 120, 7, "white"),
        line((138, 60), (148, 54)), line((140, 76), (152, 76)), line((62, 60), (52, 54)),
        line((8, 140), (152, 140)),
    ])


@art("combined-ratio-point", "One point of combined ratio")
def _():
    out = [rect(20, 20, 120, 120, MIST)]
    for i in range(1, 10):
        out += [line((20 + i * 12, 20), (20 + i * 12, 140), width=1, color=LAVENDER),
                line((20, 20 + i * 12), (140, 20 + i * 12), width=1, color=LAVENDER)]
    out += [rect(20, 20, 120, 120, "none"), rect(116, 116, 12, 12, PURPLE), check(136, 112, 11, LILAC)]
    return "\n".join(out)


@art("four-week-assessment", "The 4-week assessment")
def _():
    out = [shadow_doc(12, 14, 56, 66, PEACH, dx=6, dy=6),
           doc(12, 14, 56, 66, lines=[(20, 30), (32, 36), (44, 24)]),
           line((74, 47), (88, 47)), arrow_head(88, 47, "right"),
           doc(92, 14, 60, 72, lines=[(20, 30), (32, 40), (44, 34), (56, 28)], hl=1, hl_color=ORANGE)]
    for i in range(4):
        x = 12 + i * 36
        out.append(rect(x, 102, 32, 32, ORANGE if i == 3 else PEACH))
    out += [check(136, 118, 10, "white"), line((12, 146), (148, 146))]
    return "\n".join(out)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for stem, title, fn in ART:
        (OUT / f"{stem}.svg").write_text(svg(fn(), title))
    print(f"illustrations/new/: {len(ART)} drawn")


if __name__ == "__main__":
    main()
